import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, BarChart3, CheckCircle2, Download, Eye, FlaskConical, Layers3, Search, ShieldAlert, Target, Users } from 'lucide-react'
import type { AuditEvent, DashboardData, ImpactResult, SimulationRequest, ThreatResult } from '../types'
import type { ValidationMetrics } from '../types/navigation'
import { getValidationMetrics } from '../services/validation'
import { exportAnalyticsCsv, exportJson, exportRecoveryCsv } from '../utils/export'
import { dateTime, decimal, percent, shortId } from '../utils/format'
import { AttackControl } from '../components/AttackControl/AttackControl'
import { ClientTable } from '../components/ClientTable/ClientTable'
import { ImpactPanel } from '../components/ImpactPanel/ImpactPanel'
import { ModelMetrics } from '../components/ModelMetrics/ModelMetrics'
import { RecoveryPanel } from '../components/RecoveryPanel/RecoveryPanel'
import { RoundMonitor } from '../components/RoundMonitor/RoundMonitor'
import { ThreatPanel } from '../components/ThreatPanel/ThreatPanel'
import { FederationNetwork } from '../components/shared/FederationNetwork'
import { LineChart } from '../components/shared/LineChart'
import { ComparisonCard, Drawer, EmptyState, MetricCard, PageHeader, Panel, StatusBadge } from '../components/shared/Ui'

const realDataNote = 'All values on this page are returned by the active run API.'

export function SimulationPage({ data, onStart, starting }: { data: DashboardData; onStart: (request: SimulationRequest) => Promise<void>; starting: boolean }) {
  const [round, setRound] = useState<number | null>(data.run?.current_round || null)
  useEffect(() => setRound(data.run?.current_round || null), [data.run?.run_id, data.run?.current_round])
  return <main className="page"><PageHeader eyebrow="Controlled experimentation" title="Simulation control" description="Configure a reproducible federation and launch a backend-supported attack scenario." /><div className="content-grid simulation-layout"><AttackControl onStart={onStart} running={starting} expanded /><div className="simulation-side"><Panel title="Execution guardrails" eyebrow="Contract aware"><ul className="guardrail-list"><li><CheckCircle2 />Scenario names match the API schema</li><li><CheckCircle2 />Attacker count cannot exceed clients</li><li><CheckCircle2 />Attack start stays within configured rounds</li><li><CheckCircle2 />Ground truth is not passed to detection</li></ul></Panel><RoundMonitor run={data.run} rounds={data.rounds} selectedRound={round} onSelectRound={setRound} /></div></div></main>
}

export function RoundsPage({ data }: { data: DashboardData }) {
  const [selected, setSelected] = useState(data.rounds.at(-1)?.round_id || null)
  const current = data.rounds.find((item) => item.round_id === selected) || null
  const metric = data.metrics.find((item) => item.round_id === selected)
  const threats = data.threats.filter((item) => item.round_id === selected)
  return <main className="page"><PageHeader eyebrow="Federation chronology" title="Round operations" description="Inspect aggregation, evaluation, mitigation and recovery one round at a time." /><ModelMetrics metrics={data.metrics} /><Panel title="Round ledger" eyebrow="Persisted backend rounds" action={<span className="table-count">{data.rounds.length} rounds</span>}>{!data.rounds.length ? <EmptyState title="No rounds available" description="Launch a simulation to populate the round ledger." /> : <div className="table-scroll"><table><thead><tr><th>Round</th><th>Status</th><th>Model</th><th>Updates</th><th>Accepted</th><th>Quarantined</th><th>Recovery</th><th><span className="sr-only">Inspect</span></th></tr></thead><tbody>{data.rounds.map((item) => <tr key={item.round_id} className="clickable-row" onClick={() => setSelected(item.round_id)}><td><strong>R{item.round_id}</strong></td><td><StatusBadge value={item.status} /></td><td>{shortId(item.model_version, 18)}</td><td>{item.update_count}</td><td>{item.accepted_count}</td><td>{item.quarantined_count}</td><td><StatusBadge value={item.recovery_triggered ? 'TRIGGERED' : 'NOT REQUIRED'} /></td><td><button className="icon-button" aria-label={`Inspect round ${item.round_id}`}><Eye /></button></td></tr>)}</tbody></table></div>}</Panel><Drawer open={!!current} title={current ? `Round ${current.round_id}` : ''} subtitle="Round inspector" onClose={() => setSelected(null)}>{current && <><div className="drawer-status"><StatusBadge value={current.status} /><StatusBadge value={current.recovery_triggered ? 'RECOVERY TRIGGERED' : 'CLEAR'} /></div><div className="definition-grid"><div><dt>Accuracy</dt><dd>{percent(metric?.accuracy)}</dd></div><div><dt>Loss</dt><dd>{decimal(metric?.loss)}</dd></div><div><dt>Updates</dt><dd>{current.update_count}</dd></div><div><dt>Accepted</dt><dd>{current.accepted_count}</dd></div><div><dt>Quarantined</dt><dd>{current.quarantined_count}</dd></div><div><dt>Threats</dt><dd>{threats.filter((item) => item.threat_level !== 'SAFE').length}</dd></div><div className="wide"><dt>Model version</dt><dd>{current.model_version || '—'}</dd></div></div></>}</Drawer></main>
}

export function ClientsPage({ data }: { data: DashboardData }) {
  return <main className="page"><PageHeader eyebrow="Federated participants" title="Client intelligence" description="Search, compare and investigate the latest evidence for every participating client." /><FederationNetwork clients={data.clients} threats={data.threats} /><ClientTable clients={data.clients} threats={data.threats} impacts={data.impacts} /></main>
}

export function ThreatsPage({ data }: { data: DashboardData }) {
  const [selected, setSelected] = useState<ThreatResult | null>(null)
  const latestRound = data.run?.current_round || data.rounds.at(-1)?.round_id
  const latest = data.threats.filter((item) => item.round_id === latestRound)
  const byRound = data.rounds.map((round) => { const items = data.threats.filter((item) => item.round_id === round.round_id); return { round: round.round_id, average: items.length ? items.reduce((sum, item) => sum + item.threat_score, 0) / items.length : 0 } })
  const suspicious = latest.filter((item) => item.threat_level === 'SUSPICIOUS')
  const malicious = latest.filter((item) => item.threat_level === 'MALICIOUS')
  return <main className="page"><PageHeader eyebrow="Detection intelligence" title="Threat analysis" description="Trace Sentinel classifications, signal evidence and response decisions." /><section className="metric-grid"><MetricCard label="Analyzed updates" value={data.threats.length ? String(data.threats.length) : '—'} context="Across the selected run" icon={<Layers3 />} /><MetricCard label="Suspicious clients" value={latest.length ? String(suspicious.length) : '—'} context="Latest completed round" tone="warning" icon={<AlertTriangle />} /><MetricCard label="Malicious clients" value={latest.length ? String(malicious.length) : '—'} context="Latest completed round" tone="danger" icon={<ShieldAlert />} /><MetricCard label="Peak threat score" value={data.threats.length ? decimal(Math.max(...data.threats.map((item) => item.threat_score))) : '—'} context="Backend threat score" tone="accent" icon={<Target />} /></section><div className="content-grid two-column"><ThreatPanel threats={latest} /><Panel title="Threat evolution" eyebrow="Average score by round">{byRound.length ? <LineChart labels={byRound.map((item) => item.round)} series={[{ label: 'Threat', values: byRound.map((item) => item.average), className: 'line-danger' }]} valueFormatter={(value) => value.toFixed(2)} ariaLabel="Average threat score by round" /> : <EmptyState title="No threat history" description="Threat history will appear after a run completes rounds." />}</Panel></div><Panel title="Threat inspector" eyebrow="Backend-provided decisions">{!data.threats.length ? <EmptyState title="No threat evidence" description="No threat records are available for this run." /> : <div className="inspector-grid">{[...data.threats].sort((a, b) => b.threat_score - a.threat_score).slice(0, 12).map((item) => <button key={item.update_id} className="inspector-card" onClick={() => setSelected(item)}><div><strong>{item.client_id}</strong><StatusBadge value={item.threat_level} /></div><span>{decimal(item.threat_score)}</span><small>Round {item.round_id} · {item.action.replaceAll('_', ' ')}</small></button>)}</div>}</Panel><ThreatDrawer threat={selected} impact={selected ? data.impacts.find((item) => item.update_id === selected.update_id) : undefined} onClose={() => setSelected(null)} /></main>
}

function ThreatDrawer({ threat, impact, onClose }: { threat: ThreatResult | null; impact?: ImpactResult; onClose: () => void }) {
  return <Drawer open={!!threat} title={threat?.client_id || ''} subtitle="Explain decision" onClose={onClose}>{threat && <><div className="drawer-status"><StatusBadge value={threat.threat_level} /><StatusBadge value={threat.action} /></div><div className="definition-grid"><div><dt>Threat score</dt><dd>{decimal(threat.threat_score)}</dd></div><div><dt>Reputation</dt><dd>{decimal(threat.reputation_score)}</dd></div><div><dt>Anomaly</dt><dd>{decimal(threat.anomaly_score)}</dd></div><div><dt>Similarity</dt><dd>{decimal(threat.similarity_score)}</dd></div><div><dt>Estimated impact</dt><dd>{decimal(impact?.impact_score)}</dd></div><div><dt>Round</dt><dd>R{threat.round_id}</dd></div><div className="wide"><dt>Affected update</dt><dd>{threat.update_id}</dd></div></div><section className="drawer-section"><h3>Why this decision?</h3>{threat.explanation_codes.length ? <ul className="evidence-list">{threat.explanation_codes.map((reason) => <li key={reason}>{reason.replaceAll('_', ' ')}</li>)}</ul> : <p className="muted-copy">The backend did not provide explanation codes.</p>}</section></>}</Drawer>
}

export function ImpactPage({ data }: { data: DashboardData }) {
  const latestRound = data.run?.current_round || data.rounds.at(-1)?.round_id
  const latest = data.impacts.filter((item) => item.round_id === latestRound)
  const highest = [...data.impacts].sort((a, b) => b.impact_score - a.impact_score).slice(0, 10)
  const metric = data.metrics.find((item) => item.round_id === latestRound)
  const recovery = data.recoveries.filter((item) => item.recovery_status !== 'NOT_REQUIRED').at(-1)
  return <main className="page"><PageHeader eyebrow="Influence intelligence" title="Impact analysis" description="Understand which updates can move the global model and why." /><div className="content-grid two-column"><ImpactPanel impacts={latest} /><Panel title="Model comparison" eyebrow="Observed backend evaluations"><div className="comparison-grid"><ComparisonCard label="Selected round" accuracy={metric?.accuracy} loss={metric?.loss} caption={metric ? `Evaluation after round ${metric.round_id}` : 'No evaluation available'} /><ComparisonCard label="Before recovery" accuracy={recovery?.before_accuracy} loss={recovery?.before_loss} caption={recovery ? `Recovery round ${recovery.round_id}` : 'No recovery event'} /><ComparisonCard label="After recovery" accuracy={recovery?.after_accuracy} loss={recovery?.after_loss} caption={recovery?.recovery_status || 'No recovery event'} /></div></Panel></div><Panel title="Highest-impact updates" eyebrow="Ranked backend estimates" action={<span className="table-count">{data.impacts.length} estimates</span>}>{!highest.length ? <EmptyState title="No impact estimates" description="Impact estimates will appear after Sentinel evaluates updates." /> : <div className="table-scroll"><table><thead><tr><th>Client</th><th>Round</th><th>Level</th><th>Impact</th><th>Influence</th><th>Weight</th><th>Update</th></tr></thead><tbody>{highest.map((item) => <tr key={item.update_id}><td><strong>{item.client_id}</strong></td><td>R{item.round_id}</td><td><StatusBadge value={item.impact_level} /></td><td>{decimal(item.impact_score)}</td><td>{decimal(item.influence_estimate)}</td><td>{decimal(item.aggregation_weight)}</td><td>{shortId(item.update_id, 18)}</td></tr>)}</tbody></table></div>}</Panel></main>
}

export function RecoveryPage({ data }: { data: DashboardData }) {
  const runId = data.run?.run_id
  const latest = data.recoveries.filter((item) => item.recovery_status !== 'NOT_REQUIRED').at(-1)
  const lifecycle = ['Attack detected', 'Update identified', 'Quarantine', 'Selective recovery', 'Re-aggregation', 'Evaluation', 'Recovered model']
  return <main className="page"><PageHeader eyebrow="Selective restoration" title="Recovery operations" description="Recover trusted model state without blindly retraining the entire federation." actions={<button className="secondary-button" disabled={!runId} onClick={() => runId && exportRecoveryCsv(data, runId)}><Download />Recovery CSV</button>} /><div className="content-grid recovery-layout"><RecoveryPanel recoveries={data.recoveries} onExport={() => runId && exportRecoveryCsv(data, runId)} /><Panel title="Recovery lifecycle" eyebrow="Operational sequence"><ol className="lifecycle">{lifecycle.map((step, index) => <li key={step} className={latest ? 'complete' : index === 0 ? 'idle' : ''}><span>{index + 1}</span><div><strong>{step}</strong><small>{latest ? `Recorded in recovery ${shortId(latest.recovery_id)}` : 'Awaiting a qualifying event'}</small></div></li>)}</ol></Panel></div>{latest && <Panel title="Before / recovery comparison" eyebrow="Persisted recovery metrics"><div className="comparison-grid"><ComparisonCard label="Before recovery" accuracy={latest.before_accuracy} loss={latest.before_loss} /><ComparisonCard label="After recovery" accuracy={latest.after_accuracy} loss={latest.after_loss} /><article className="comparison-card emphasis"><span>Recovery gain</span><div><small>Accuracy restored</small><strong>{latest.before_accuracy != null && latest.after_accuracy != null ? percent(latest.after_accuracy - latest.before_accuracy) : '—'}</strong></div><p>{latest.trigger}</p></article></div></Panel>}</main>
}

export function ValidationPage() {
  const [metrics, setMetrics] = useState<ValidationMetrics | null>(null)
  useEffect(() => { void getValidationMetrics().then(setMetrics) }, [])
  if (!metrics) return <main className="page"><PageHeader eyebrow="Engine assurance" title="Validation laboratory" description="The UI contract is ready; connect a validation endpoint to publish verified results." /><Panel title="Validation unavailable" eyebrow="API required"><EmptyState title="No validation endpoint connected" description="Production mode never substitutes mock values for validation truth." /></Panel></main>
  const d = metrics.detection
  return <main className="page"><PageHeader eyebrow="Engine assurance" title="Validation laboratory" description="Preview the planned ground-truth comparison layer." actions={<span className="dev-badge"><FlaskConical />Development preview · mock service</span>} /><div className="mock-warning"><AlertTriangle /><span><strong>Illustrative interface only.</strong> These values come from an isolated development mock and are not FedSentinel results.</span></div><section className="metric-grid metric-grid-five"><MetricCard label="Precision" value={percent(d.precision)} context="TP / predicted positive" /><MetricCard label="Recall" value={percent(d.recall)} context="Detection rate" /><MetricCard label="F1 score" value={decimal(d.f1)} context="Harmonic mean" /><MetricCard label="False positive rate" value={percent(d.falsePositiveRate)} context="FP / benign" /><MetricCard label="Detection rate" value={percent(d.detectionRate)} context="Ground-truth attackers found" /></section><div className="content-grid two-column"><Panel title="Detection validation" eyebrow="Confusion matrix"><div className="confusion-grid"><div className="semantic-success"><span>True positive</span><strong>{d.tp}</strong></div><div className="semantic-danger"><span>False positive</span><strong>{d.fp}</strong></div><div><span>True negative</span><strong>{d.tn}</strong></div><div className="semantic-warning"><span>False negative</span><strong>{d.fn}</strong></div></div></Panel><Panel title="Threat-score separation" eyebrow="Threshold preview"><div className="distribution-preview"><div><span>Benign scores</span><div>{metrics.threatScores.benign.map((value) => <i key={value} style={{ left: `${value * 100}%` }} />)}</div></div><div className="attacker"><span>Attacker scores</span><div>{metrics.threatScores.attacker.map((value) => <i key={value} style={{ left: `${value * 100}%` }} />)}</div></div><small style={{ left: `${metrics.threatScores.threshold * 100}%` }}>Threshold</small></div></Panel></div><div className="content-grid two-column"><Panel title="Impact validation" eyebrow="Predicted vs observed"><div className="comparison-grid"><ComparisonCard label="Predicted degradation" accuracy={metrics.impact.predictedDegradation} /><ComparisonCard label="Observed degradation" accuracy={metrics.impact.observedDegradation} /><ComparisonCard label="Absolute error" accuracy={metrics.impact.absoluteError} /></div></Panel><Panel title="Recovery validation" eyebrow="Effectiveness preview"><div className="definition-grid"><div><dt>Attack-induced loss</dt><dd>{percent(metrics.recovery.inducedLoss)}</dd></div><div><dt>Recovered performance</dt><dd>{percent(metrics.recovery.recoveredPerformance)}</dd></div><div><dt>Recovery gain</dt><dd>{percent(metrics.recovery.gain)}</dd></div><div><dt>Effectiveness</dt><dd>{percent(metrics.recovery.effectiveness)}</dd></div></div></Panel></div></main>
}

export function AuditPage({ data }: { data: DashboardData }) {
  const [query, setQuery] = useState(''); const [severity, setSeverity] = useState('ALL'); const [eventType, setEventType] = useState('ALL')
  const types = [...new Set(data.audit.map((event) => event.event_type))]
  const events = useMemo(() => data.audit.filter((event) => severity === 'ALL' || event.severity === severity).filter((event) => eventType === 'ALL' || event.event_type === eventType).filter((event) => `${event.message} ${event.client_id || ''} ${event.update_id || ''}`.toLowerCase().includes(query.toLowerCase())), [data.audit, query, severity, eventType])
  return <main className="page"><PageHeader eyebrow="System observability" title="Security audit log" description="Search the persisted event trail for simulation, detection, response and recovery activity." /><Panel title="Event stream" eyebrow="Persisted backend events" action={<span className="table-count">{events.length} events</span>}><div className="table-toolbar"><label className="search-field"><span className="sr-only">Search audit events</span><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search events, clients or updates" /></label><select aria-label="Filter audit severity" value={severity} onChange={(e) => setSeverity(e.target.value)}><option value="ALL">All severities</option><option value="INFO">Info</option><option value="WARN">Warning</option><option value="ALERT">Alert</option></select><select aria-label="Filter audit event type" value={eventType} onChange={(e) => setEventType(e.target.value)}><option value="ALL">All event types</option>{types.map((type) => <option key={type} value={type}>{type.replaceAll('_', ' ')}</option>)}</select></div>{!events.length ? <EmptyState title="No matching events" description="Change the filters or select another run." /> : <div className="table-scroll"><table><thead><tr><th>Timestamp</th><th>Severity</th><th>Event</th><th>Round</th><th>Client</th><th>Message</th></tr></thead><tbody>{[...events].reverse().map((event: AuditEvent) => <tr key={event.id}><td>{dateTime(event.timestamp)}</td><td><StatusBadge value={event.severity} /></td><td>{event.event_type.replaceAll('_', ' ')}</td><td>{event.round_id ? `R${event.round_id}` : '—'}</td><td>{event.client_id || '—'}</td><td className="message-cell">{event.message}</td></tr>)}</tbody></table></div>}</Panel></main>
}

export function NoRunPage({ onNavigate }: { onNavigate: (path: string) => void }) {
  return <main className="page"><PageHeader eyebrow="FedSentinel workspace" title="No simulation selected" description="Launch a simulation to begin collecting federation security evidence." /><Panel title="Start with a controlled run" eyebrow="No backend data"><EmptyState title="No simulation data yet" description={realDataNote} icon={<Users />} /><button className="primary-button centered-action" onClick={() => onNavigate('/simulation')}>Open simulation control</button></Panel></main>
}

export function ExportButtons({ data }: { data: DashboardData }) {
  const runId = data.run?.run_id
  return <><button className="secondary-button" disabled={!runId} onClick={() => runId && exportJson(data, runId)}><Download />Export JSON</button><button className="secondary-button" disabled={!runId} onClick={() => runId && exportAnalyticsCsv(data, runId)}><BarChart3 />Export analytics</button></>
}
